server:
  port: 8888
  
spring: 
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: git@github.com:francitonioferreiraalves/upgrad-backend-microservices.git  
          default-label: main
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost